[package]
name = "jmclib"
version = "0.1.0"
edition = "2021"


[dependencies]
toml = "0.5"
serde = { version = "1" }
tempfile = "3"
slog = "2.5"
slog-term = "2.5"
atty = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
